const $=s=>document.querySelector(s);
let catalog,initialCatalog,scenario,current=null,references=[],busy=false,stale=true;
const money=minor=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(minor)/100);
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function status(message,error=false){$('#status').textContent=message;$('#status').className=error?'error':'';}
function markStale(message='Inputs changed. Rebuild to update the programme.'){stale=true;$('#export').disabled=true;status(message);if(current)$('#source-label').textContent=(current.mode==='live'?'Live Qloo order':'Authored example')+' · update needed';}
async function api(path,body){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`);return data;}
function constraints(){return {...scenario.constraints,totalBudgetMinor:String(Math.round(Number($('#budget').value)*100)),language:$('#language').value,minDistinctMedia:Number($('#diversity').value),slots:scenario.constraints.slots.map(s=>({...s,maxMinutes:Number($('#minutes').value)}))};}
function setBusy(value){busy=value;document.querySelectorAll('input,select,button').forEach(n=>n.disabled=value);$('#export').disabled=value||stale||!current||current.plan.status!=='feasible';}
async function plan({repair=false,removed=[]}={}){
 if(busy||!$('#settings').reportValidity())return;
 stale=true;setBusy(true);status(repair?'Checking alternatives and repairing the programme…':'Checking the catalogue and building three sessions…');
 try{const result=await api('/api/plan',{catalog,constraints:constraints(),mode:$('#mode').value,references,previousPlan:repair?current?.plan:null,unavailableItemIds:removed});current=result;stale=false;renderPlan(result);}
 catch(err){status(err.message,true);}
 finally{setBusy(false);}
}
function renderPlan(result){
 const p=result.plan;$('#sessions').replaceChildren();$('#changes').replaceChildren();$('#totals').replaceChildren();$('#source-label').textContent=result.mode==='live'?'Live Qloo order':'Authored example';
 status(p.status==='feasible'?'Three discussion sessions pass the exercise constraints. Review the material and permissions before arranging a real event.':'No complete programme fits this brief. Adjust the constraints or add eligible resources.',p.status!=='feasible');
 if(p.totals){for(const [label,value]of [['Total',money(p.totals.costMinor)],['Remaining',money(p.totals.remainingBudgetMinor)],['Discussion',`${p.totals.activityMinutes} min`]]){const n=el('span');n.append(el('strong',value),document.createTextNode(` ${label.toLowerCase()}`));$('#totals').append(n);}}
 else{const n=el('div',undefined,'empty');n.append(el('h3','Something needs to give.'));const list=el('ul');p.failures.filter(f=>f.code!=='NO_FEASIBLE_CYCLE').forEach(f=>list.append(el('li',f.message)));n.append(list);$('#sessions').append(n);}
 p.sessions.forEach((s,i)=>{const n=el('article',undefined,'session'+(p.changes.some(c=>c.slotId===s.slotId)?' changed':''));n.append(el('span',String(i+1).padStart(2,'0'),'number'));const body=el('div');body.append(el('p',s.medium==='movie'?'Film':s.medium==='artist'?'Music':'Book','medium'),el('h3',s.name),el('p',s.activity),el('p',`${s.language==='es'?'Spanish':'English'} discussion · ${s.unusedMinutes} min spare`));const meta=el('div',undefined,'meta');meta.append(el('span',`${s.durationMinutes} min · ${money(s.costMinor)}`));const b=el('button','Resource unavailable','remove-resource');b.type='button';b.addEventListener('click',()=>{const item=catalog.items.find(x=>x.id===s.itemId);item.availability='unavailable';renderCatalogue();plan({repair:true,removed:[s.itemId]});});meta.append(b);n.append(body,meta);$('#sessions').append(n);});
 if(p.changes.length){const n=el('div',undefined,'change-note');n.append(el('strong',`${p.changes.length} session changed · ${p.objective.preservedSessionCount} preserved`));p.changes.forEach(c=>n.append(el('p',`${catalog.items.find(x=>x.id===c.previousItemId)?.name} → ${catalog.items.find(x=>x.id===c.replacementItemId)?.name}`)));$('#changes').append(n);}
 $('#trace').replaceChildren();result.trace.forEach(t=>{const n=el('li');n.append(el('strong',t.tool.replaceAll('_',' ')+' — '),document.createTextNode(t.summary));$('#trace').append(n);});
 $('#evidence').replaceChildren(el('p',result.agent),el('p',p.provenance.ranking.notice));for(const e of result.evidence){$('#evidence').append(el('h3',e.medium));const list=el('ol');e.returned.forEach(r=>list.append(el('li',`${r.name} · ${r.entityId}`)));$('#evidence').append(list);}$('#export').disabled=p.status!=='feasible';
}
function renderCatalogue(){const root=$('#catalogue');root.replaceChildren();$('#catalogue-count').textContent=`${catalog.items.filter(i=>i.availability==='available').length} marked available / ${catalog.items.length} resources`;catalog.items.forEach((item,index)=>{
 const row=el('article',undefined,'resource');const title=el('div');title.append(el('h3',item.name),el('span',`${item.medium} · ${item.activity}`,'sub'));row.append(title);
 const field=(label,prop,type,options)=>{const wrap=el('div'),id=`resource-${index}-${prop}`,l=el('label',label);l.htmlFor=id;const input=el(type==='select'?'select':'input');input.id=id;if(type==='select')options.forEach(([v,t])=>{const o=el('option',t);o.value=v;input.append(o);});else{input.type='number';input.min='0';input.max=prop==='costMinor'?'10000':'600';input.step=prop==='costMinor'?'0.01':'1';}input.value=prop==='costMinor'?(item[prop]===null?'':Number(item[prop])/100):(item[prop]??'');input.addEventListener('change',()=>{item[prop]=type==='select'?input.value:input.value===''?null:prop==='costMinor'?String(Math.round(Number(input.value)*100)):Number(input.value);status('Catalogue changed. Rebuild to check the updated programme.');$('#export').disabled=true;});wrap.append(l,input);return wrap;};
 row.append(field('Availability','availability','select',[['available','Available'],['unavailable','Unavailable'],['unknown','Unknown']]),field('Minutes','durationMinutes','number'),field('Cost (USD)','costMinor','number'),field('Permission','permissionStatus','select',[['assumed-for-demo','Assumed in example'],['unknown','Unknown'],['not-allowed','Not allowed']]));
 const identity=el('div',undefined,'identity');identity.append(el('span',item.qlooConfirmed?`Connected: ${item.qlooName}`:'Qloo identity not connected'));const connect=el('button','Connect Qloo identity');connect.type='button';const results=el('div',undefined,'connection-results');connect.addEventListener('click',async()=>{if(busy)return;setBusy(true);results.textContent='Searching…';try{const data=await api('/api/search',{query:item.name,medium:item.medium});showChoices(results,data.entities,chosen=>{item.qlooId=chosen.id;item.qlooConfirmed=true;item.qlooName=chosen.name;renderCatalogue();markStale('Catalogue identity connected. Rebuild to use the updated catalogue.');});}catch(e){results.textContent=e.message;}finally{setBusy(false);}});identity.append(connect,results);row.append(identity);root.append(row);
});}
function showChoices(root,entities,choose){root.replaceChildren();if(!entities.length)root.append(el('p','No match found. No identity was assigned.','helper'));entities.forEach(e=>{const b=el('button',e.name,'pick');b.type='button';b.append(el('span',`${e.types.join(', ')}${e.year?' · '+e.year:''} · ${e.id}`));if(e.description)b.append(el('span',e.description));b.append(el('span','Choose only if this is the intended work or artist.'));b.addEventListener('click',()=>choose(e));root.append(b);});}
function renderReferences(){const root=$('#references');root.replaceChildren();if(!references.length)root.append(el('p','No references selected.','helper'));references.forEach((e,i)=>{const n=el('div',e.name,'reference'),b=el('button','×');b.type='button';b.setAttribute('aria-label',`Remove ${e.name}`);b.addEventListener('click',()=>{if(busy)return;references.splice(i,1);renderReferences();markStale('Reference removed. Rebuild to update the programme.');});n.append(b);root.append(n);});}
$('#search').addEventListener('click',async()=>{if(busy)return;setBusy(true);try{const data=await api('/api/search',{query:$('#query').value,medium:$('#medium').value});showChoices($('#search-results'),data.entities,e=>{if(busy||references.some(r=>r.id===e.id))return;if(references.length>=5){status('Choose at most five references.',true);return;}references.push(e);renderReferences();$('#search-results').replaceChildren();markStale('Reference added. Rebuild to update the programme.');});}catch(e){$('#search-results').replaceChildren(el('p',e.message,'helper'));}finally{setBusy(false);}});
$('#settings').addEventListener('submit',e=>{e.preventDefault();plan();});$('#mode').addEventListener('change',()=>{if($('#mode').value==='live')$('#reference-tools').open=true;status('Source changed. Rebuild to apply it.');$('#export').disabled=true;});
$('#reset').addEventListener('click',()=>{if(busy||!initialCatalog)return;catalog=structuredClone(initialCatalog);HTMLFormElement.prototype.reset.call($('#settings'));references=[];renderReferences();renderCatalogue();current=null;plan();});
document.addEventListener('change',e=>{if(e.target.matches('input,select')&&e.target.id!=='query'&&e.target.id!=='medium')markStale();});
$('#export').addEventListener('click',()=>{if(!current||stale||busy)return;const blob=new Blob([JSON.stringify({...current,catalogue:catalog},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='culture-weave-programme.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
try{[catalog,scenario]=await Promise.all(['fixtures/catalog.json','fixtures/planning-scenario.json'].map(async p=>(await fetch(p)).json()));catalog.items=catalog.items.slice(0,6);initialCatalog=structuredClone(catalog);const config=await(await fetch('/api/status')).json();$('#connection').textContent=config.qlooConfigured?'Qloo configured on the server. Live results require confirmed identities.':'Qloo is not connected yet. The example works; live search and ranking are unavailable.';renderCatalogue();await plan();}catch(e){status(`Could not load the programme: ${e.message}`,true);}
